name: Telegram notification

concurrency:
  group: notification-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows:
      - Build
      - Deploy Next.js site to Pages
      - Release new version
      - Publish Docker image to GHCR
    branches:
      - main
    types:
      - completed
  workflow_dispatch:
jobs:
  notification:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHATID }}
          token: ${{ secrets.BOTTOKEN }}
          format: markdown
          message: |
            Code Deployed: ${{ github.repository }}

            ${{ github.actor }} created commit:
            ${{ github.event.workflow_run.head_commit.message }}

            [View action run](${{ github.event.workflow_run.html_url }})
            [Cancel action run](${{ github.event.workflow_run.cancel_url }})

            Workflow: ${{ github.event.workflow_run.name }}
            Job status: ${{ github.event.workflow_run.conclusion == 'success' && '✅' || '🚫' }} ${{ github.event.workflow_run.conclusion }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

              - name: Publish workflow summary
                  if: always()
                  shell: bash
                  run: |
                      echo "## Notification – Summary" >> "$GITHUB_STEP_SUMMARY"
                      echo "Triggered workflow: ${{ github.event.workflow_run.name }}" >> "$GITHUB_STEP_SUMMARY"
                      echo "Conclusion: ${{ github.event.workflow_run.conclusion }}" >> "$GITHUB_STEP_SUMMARY"
                      echo "Run URL: ${{ github.event.workflow_run.html_url }}" >> "$GITHUB_STEP_SUMMARY"
